Repository qavajs/steps-playwright, pull requests merged in 2023-12, with the labels that each got.

#92 :rocket: introduced browserManager object to control all launched b…
  CHANGELOG.md
  README.md
  global.d.ts
  package-lock.json
  package.json
  src/browserManager.ts
  src/hooks.ts
  src/multiBrowser.ts
  test-e2e/features/electron/electron.feature
  test-e2e/features/multiBrowser.feature
  test-e2e/webui.ts
  test/browserManager.spec.ts
  vitest.config.js
Labels: enhancement

#94 Replace type to fill
  CHANGELOG.md
  package.json
  src/actions.ts
Labels: enhancement

#98 - added existence waiter before value waits to avoid promise reject w…
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/browserManager.ts
  src/hooks.ts
  src/validations.ts
  src/waits.ts
  test-e2e/webui.ts
Labels: bug, enhancement

#100 added present timeout for value waits
  CHANGELOG.md
  package-lock.json
  src/validations.ts
  src/waits.ts
Labels: bug

#101 added _I tap {string}_ step
  CHANGELOG.md
  package-lock.json
  package.json
  src/actions.ts
  test-e2e/apps/actions.html
  test-e2e/features/actions.feature
  test-e2e/page_object/index.ts
  test-e2e/step-definitions/index.ts
  test-e2e/webui.ts
  tsconfig.json
Labels: enhancement
