Repository qavajs/steps-playwright, pull requests merged in 2023-05, with the labels that each got.

#45 implemented drag-n-drop step
  CHANGELOG.md
  README.md
  package-lock.json
  package.json
  src/actions.ts
  test-e2e/apps/dragdrop.html
  test-e2e/features/dragdrop.feature
  test-e2e/memory/index.ts
  test-e2e/page_object/index.ts
Labels: enhancement

#46 updated exports of mock and poDefine
  CHANGELOG.md
  index.js
  package-lock.json
  package.json
  src/mock.ts
Labels: bug

#47 added types to global members
  CHANGELOG.md
  README.md
  global.d.ts
  package-lock.json
  package.json
Labels: enhancement

#48 added _I switch to 'IFrame' frame_
  CHANGELOG.md
  package-lock.json
  package.json
  src/actions.ts
  test-e2e/apps/actions.html
  test-e2e/apps/frame.html
  test-e2e/apps/innerFrame.html
  test-e2e/features/actions.feature
  test-e2e/page_object/index.ts
Labels: enhancement

#49 added _I switch to 'window name or title' window_
  CHANGELOG.md
  package-lock.json
  package.json
  src/actions.ts
  test-e2e/features/actions.feature
  test-e2e/features/waits.feature
Labels: enhancement

#50 Switch window step fix
  .gitignore
  src/actions.ts
  test-e2e/features/actions.feature
  test-e2e/features/memory.feature
  test-e2e/features/validations.feature
  test-e2e/step-definitions/index.ts
Labels: bug, enhancement

#52 added _I open new tab_
  CHANGELOG.md
  src/actions.ts
  test-e2e/features/actions.feature
Labels: enhancement

#51 added multi browser support
  .github/workflows/pull-request.yml
  CHANGELOG.md
  README.md
  global.d.ts
  index.js
  package-lock.json
  package.json
  src/hooks.ts
  src/multiBrowser.ts
  test-e2e/apps/mock.html
  test-e2e/features/mock.feature
  test-e2e/features/multiBrowser.feature
  test-e2e/features/waits.feature
  test-e2e/webui.ts
Labels: enhancement

#53 Enabled disabled
  .github/workflows/npm-publish.yml
  .github/workflows/pull-request.yml
  CHANGELOG.md
  jest.config.js
  package-lock.json
  package.json
  src/conditionWait.ts
  src/hooks.ts
  test-e2e/apps/waits.html
  test-e2e/features/waits.feature
  test-e2e/page_object/index.ts
  test/utilsImport.spec.ts
  vitest.config.js
Labels: enhancement

#54 fixed regexp in dynamic po steps
  CHANGELOG.md
  package-lock.json
  package.json
  src/hooks.ts
  src/poDefine.ts
  test-e2e/features/dynamicPageObjects.feature
Labels: bug
